# CMake generated Testfile for 
# Source directory: /mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest
# Build directory: /mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rostest_gtest_test_permuter "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results/rostest/gtest-test_permuter.xml" "--return-code" "/mnt/dav/Projekt/Software/Raspberry PI/devel_isolated/rostest/lib/rostest/test_permuter --gtest_output=xml:/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results/rostest/gtest-test_permuter.xml")
add_test(_ctest_rostest_rostest_test_hztest0.test "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results/rostest/rostest-test_hztest0.xml" "--return-code" "/mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest/scripts/rostest --pkgdir=/mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest --package=rostest --results-filename test_hztest0.xml --results-base-dir \"/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results\" /mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest/test/hztest0.test ")
add_test(_ctest_rostest_rostest_test_hztest.test "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results/rostest/rostest-test_hztest.xml" "--return-code" "/mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest/scripts/rostest --pkgdir=/mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest --package=rostest --results-filename test_hztest.xml --results-base-dir \"/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results\" /mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest/test/hztest.test ")
add_test(_ctest_rostest_rostest_test_clean_master.test "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results/rostest/rostest-test_clean_master.xml" "--return-code" "/mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest/scripts/rostest --pkgdir=/mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest --package=rostest --results-filename test_clean_master.xml --results-base-dir \"/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results\" /mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest/test/clean_master.test ")
add_test(_ctest_rostest_rostest_test_distro_version.test "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results/rostest/rostest-test_distro_version.xml" "--return-code" "/mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest/scripts/rostest --pkgdir=/mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest --package=rostest --results-filename test_distro_version.xml --results-base-dir \"/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/rostest/test_results\" /mnt/dav/Projekt/Software/Raspberry PI/src/ros_comm/rostest/test/distro_version.test ")
subdirs(gtest)
