# CMake generated Testfile for 
# Source directory: /mnt/dav/Projekt/Software/Raspberry PI/src/ros/roslib
# Build directory: /mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_roslib_nosetests_test "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/test_results/roslib/nosetests-test.xml" "--return-code" "/usr/bin/cmake -E make_directory /mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/test_results/roslib" "/usr/bin/nosetests-2.7 -P --process-timeout=60 --where=/mnt/dav/Projekt/Software/Raspberry PI/src/ros/roslib/test --with-xunit --xunit-file=/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/test_results/roslib/nosetests-test.xml")
add_test(_ctest_roslib_gtest_roslib-utest "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/test_results/roslib/gtest-roslib-utest.xml" "--working-dir" "/mnt/dav/Projekt/Software/Raspberry PI/src/ros/roslib" "--return-code" "/mnt/dav/Projekt/Software/Raspberry PI/devel_isolated/roslib/lib/roslib/roslib-utest --gtest_output=xml:/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/test_results/roslib/gtest-roslib-utest.xml")
add_test(_ctest_roslib_gtest_roslib-test_package "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/test_results/roslib/gtest-roslib-test_package.xml" "--return-code" "/mnt/dav/Projekt/Software/Raspberry PI/devel_isolated/roslib/lib/roslib/roslib-test_package --gtest_output=xml:/mnt/dav/Projekt/Software/Raspberry PI/build_isolated/roslib/test_results/roslib/gtest-roslib-test_package.xml")
subdirs(gtest)
